### ISSUE TITLE
Images issues

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate#1]
- `titlepage.svg` not correct height
- Missing standard styling for `<figure>`s, see "Complete HTML and CSS markup examples" in https://standardebooks.org/contribute/semantics#images
- Images in text are really big. That's good, but we need to size them to be more a more reasonable size for the viewport. Also, for retina screens we generally want to half-size everything where possible. Once you include the required CSS above, wider images should usually look OK because the style enforces a max-width. But for taller images like `map-a.png` and `map-c.png` we should enforce a height in `local.css`. Otherwise the text in the images will look huge compared to the text on the page, and the image could take up several viewport pages in height.
Again, for retina compatibility usually half-sizing things works best.

**Comment by robinwhittleton** [comment]
- Titlepage fixed in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/a82fbe049a43c518f7bd56e9d4178e2b7b892472
- Styling fixed in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/5438c4ef9f5f748834c36868bc5ee1a0c9ec5a4c
