### ISSUE TITLE
local.css

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate#2]
- Remove `blockquote` styling, the default is already a 1em margin and we don't want to remove the side margins.
- `[epub|type~="z3998:letter"] footer p` should have `margin-top: 1em;`
- `[epub|type~="z3998:letter"] header p` is not necessary because `p` already has `margin: 0` in `core.css`
- Instead of styling `epub:type="z3998:sender"` with `font-variant: small-caps;` please add `class="signature"` and target that for small caps instead. That's currently the standard for signatures at the moment (since signatures can appear in places that are not letters, for example an author signing a preface).

**Comment by robinwhittleton** [comment]
Good call, fixed in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/dc2f2bc52fc0e349eda7b34573708089a631980c.
