### ISSUE TITLE
Wrapping chapters in part sections

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate#3]
Each chapter should be wrapped in `<section id="part-1" epub:type="part">` (or part 2) so that we can better recompose them into a single file at a later date.

**Comment by robinwhittleton** [comment]
Oh yeah, sorry about that, I remember you reminding me about this on Dead Souls 😕 Fixed in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/16cf636a5064f0eeb90415a295c99f1f351423b0.
