### ISSUE TITLE
epub:type="fulltitle"

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate#4]
In `part-1.xhtml` and `part-2.xhtml`, I see you styled them with `epub:type="fulltitle"`. "fulltitle" is reserved for the full title of the book--that's the only element that should have that semantic. For everything else, including part names, `epub:type="title"` is sufficient. Thus, you can also remove `epub:type="title"` from the child `<span>`.

See "Sections with unnumbered titles and subtitles" in the semantics manual for the correct pattern to use here: https://standardebooks.org/contribute/semantics

**Comment by acabal** [comment]
I see you also followed the `fulltitle` pattern for chapters, and the word "chapter" is still in there. Please remove the word "chapter" from chapter `<h2>`s, and just leave the roman numerals. See "Sections with titles and chapter numbers" in the semantics manual for the pattern.

**Comment by acabal** [comment]
Once you fix the chapter titles, `lint` should also alert you that your `<title>` tags are incorrect; they require the chapter subtitle as well.

**Comment by robinwhittleton** [comment]
Oops, I’d misread the z3998 spec while working on Keats. Fixed in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/78fc2b26c6acb099a72f4fc696128b17c31d6e5d.
