### ISSUE TITLE
Content.opf suggestions

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate#7]
- For the short description, can you change "Merriman" to something *describing* who Merriman is? A reader browsing short descriptions will have no idea who Merriman is.
- In the long description, can you define what a "pit-prop" is? I had to look it up so we should probably add a quick explanation for casual readers.

Otherwise everything in there looks good!

**Comment by robinwhittleton** [comment]
Sorry, too close to the trees to see the woods :) Hopefully this is better: https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/6dab24786507c83c6b3c1865929ea71d630c4d83.
