### ISSUE TITLE
<h3> in chapter 13

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate#8]
I see there's an `<h3>` in chapter 13. However `<h#>` items are required to appear in the ToC. That blockquote definitely shouldn't go in the ToC, so you should use alternate header styling for that. Usually `<header><p>The Title</p></header>` works, styled with `header p{ font-variant: small-caps; text-align: center; margin-bottom: 1em; }`

**Comment by robinwhittleton** [comment]
Good call, I wondered about that at the time. Fixed in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/0f0f6a9c78565da976d3e7d4679636c4729f7c52.
