### ISSUE TITLE
Remove quotes around ship name in ToC

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate#9]
Generally items are _either_ italicized _or_ quoted, but not both. Ship names are italicized so quotes need to be removed in the chapter titles within the files themselves, and also in the ToC.

**Comment by acabal** [comment]
You can also remove the quotes from `<title>` tags, even though we can't put italics in `<title>`.

**Comment by SillySam** [comment]
Please explain more, thanks

**Comment by robinwhittleton** [comment]
No problem, fixed in https://github.com/robinwhittleton/freeman-wills-crofts_the-pit-prop-syndicate/commit/f84d3510d46b5660861018021b342f8d4b376f56 .
